# We allow longer lines in our style
Metrics/LineLength:
  Max: 150

# TODO/FIXME:
# At some point, we might just want to do the changes and get rid of those

Metrics/ClassLength:
  Max: 128

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 60

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
