sudo: required
services:
  - docker
language: python
python:
  - '2.7'
cache:
  directories:
    - "$HOME/.cache/pip"
git:
  depth: 3
branches:
  only:
    - master
env:
  global:
    - SKIP_CLEANUP=true
    - PIP_CACHE=$HOME/.cache/pip

stages:
  - name: test_pr
    if: type = pull_request
  - name: test
    if: (branch = master) AND (type != pull_request)

script:
  # This is the default script section that will be run for every 'test' stage
  - ddev -e validate manifest -i
  - ddev -e validate config
  - ddev -e validate service-checks
  # FIXME: fix metadata for all the integrations before enabling the following:
  # - ddev -e validate metadata ${CHECK}
  - travis_retry ddev -e test ${CHECK}

# Conditional jobs are currently buggy and verbose.
#
# https://github.com/travis-ci/beta-features/issues/28
# https://github.com/travis-ci/beta-features/issues/40
# https://github.com/travis-ci/travis-ci/issues/8295
# https://github.com/travis-ci/travis-conditions/pull/1
# https://github.com/travis-ci/travis-ci/issues/6652
jobs:
  fast_finish: true
  include:
    - stage: test_pr
      script:
        - ddev -e validate manifest -i
        - ddev -e validate config
        - ddev -e validate service-checks
        # FIXME: fix metadata for all the integrations before enabling the following:
        # - ddev -e validate metadata
        # with no params, ddev will only test integrations that are part of the branch diff
        - ddev -e test
    - stage: test
      env: CHECK=aqua
    - stage: test
      env: CHECK=eventstore
    - stage: test
      env: CHECK=reboot_required
    - stage: test
      env: CHECK=sortdb
    - stage: test
      env: CHECK=traefik

install:
  - pip install -U pip setuptools
  - pip install -r requirements-dev.txt
  - ddev config set extras .

# we should clean generated files before we save the cache
# We don't want to save .pyc files, so we'll use find and -delete
before_cache:
  - find $HOME/.cache/pip -name *.pyc -delete
