sudo: required

language: python
cache:
  directories:
    - $home/.cache/pip
    - $home/dd-agent
    - vendor/cache
python:
  - "2.7"

git:
  depth: 3

branches:
  only:
    - master

services:
  - docker

matrix:
  fast_finish: true

env:
  global:
    - NOSE_FILTER="not windows and not fixme"
    - VOLATILE_DIR=/tmp/integration-sdk-testing
    - SKIP_CLEANUP=true
    - INTEGRATIONS_DIR=$HOME/embedded
    - PIP_CACHE=$HOME/.cache/pip
    - SDK_TESTING=true
    - BUNDLE_PATH=$TRAVIS_BUILD_DIR/vendor/cache
    - DD_AGENT_BRANCH=master
    - CORE_BRANCH=master
    - REQ_LOCALS="$TRAVIS_BUILD_DIR,$HOME/dd-agent,$HOME/integrations-core"
  matrix:
    - TRAVIS_FLAVOR=default
    - TRAVIS_FLAVOR=snmpwalk
    - TRAVIS_FLAVOR=hbase_master
    - TRAVIS_FLAVOR=hbase_regionserver
    # END OF TRAVIS MATRIX

install:
  - bundle install
  - bundle package
  - git -C $HOME/dd-agent pull || git clone -b $DD_AGENT_BRANCH --depth 1 https://github.com/DataDog/dd-agent.git $HOME/dd-agent
  - git -C $HOME/integrations-core pull || git clone -b $CORE_BRANCH --depth 1 https://github.com/DataDog/integrations-core.git $HOME/integrations-core
  - echo "$HOME/dd-agent/" > $(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")/datadog-agent.pth
  - if [ -e ~/dd-agent/requirements.txt ]; then pip install -r ~/dd-agent/requirements.txt; fi
  - apt-get install -y snmp

script:
  - bundle exec rake prep_travis_ci
  - bundle exec rake ci:run
  - bundle exec rake requirements

# we should clean generated files before we save the cache
# We don't want to save .pyc files
# Since clobber only cleans the project directory,
# everything outside of it should be cleaned, too, so we'll use find and -delete
before_cache:
  - rake clobber
  - find $HOME/.cache/pip $HOME/dd-agent -name *.pyc -delete

after_script:
  - if [[ $(docker ps -a -q) ]]; then docker stop $(docker ps -a -q); fi
