version: '{branch}.{build}'
clone_depth: 3
build: off
test: off
skip_branch_with_pr: true
cache:
  - '%LOCALAPPDATA%\pip\Cache'

branches:
  only:
    - master

environment:
  PYTHON2: C:\Python27-x64
  PYTHON3: C:\Python36-x64

init:
  # Add Python 3 to PATH
  - set PATH=%PYTHON3%;%PYTHON3%\Scripts;%PATH%
  - python -c "import sys; print(sys.version)"

  # Add Python 2 to PATH before Python 3
  - set PATH=%PYTHON2%;%PYTHON2%\Scripts;%PATH%
  - python -c "import sys; print(sys.version)"

  # Test only what changed when it's a PR
  - if defined APPVEYOR_PULL_REQUEST_NUMBER ( set "CHANGED_ONLY_FLAG= --changed" ) else ( set "CHANGED_ONLY_FLAG= " )

install:
  - python -m pip install --upgrade --disable-pip-version-check pip virtualenv codecov
  - pip uninstall -y docker-py
  - pip install datadog_checks_dev[cli]
  - ddev config set extras .

test_script:
  - ddev -e validate manifest -i
  - ddev -e validate config
  - ddev -e validate service-checks
  - ddev -e validate metadata
  - ddev -e test%CHANGED_ONLY_FLAG% -c aqua eventstore sortdb traefik
