version: '{branch}.{build}'
clone_depth: 3
environment:
  PIP_CACHE: c:\projects\integrations-extras\.cache\pip
  VOLATILE_DIR: c:\projects
  PYWIN_PATH: C:\projects\integrations-extras\.cache\pywin32-py2.7.exe
  SKIP_LINT: true
  PYTHON: C:\Python27-x64
  PYTHON_VERSION: 2.7.13
  PYTHON_ARCH: 64
  PYWIN32_URL: https://downloads.sourceforge.net/project/pywin32/pywin32/Build%20219/pywin32-219.win-amd64-py2.7.exe
  PYWIN32_INSTALL_DIR: pywin32-219-py2.7-win-amd64.egg
init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
cache:
  - C:\projects\integrations-extras\.cache
  - C:\projects\integrations-extras\vendor\cache
install:
  - if not exist %PIP_CACHE% mkdir %PIP_CACHE%
  - ps: If (-Not (Test-Path $env:PYWIN_PATH)) {(new-object net.webclient).DownloadFile("$env:PYWIN32_URL", "$env:PYWIN_PATH")}
  - "%PYTHON%/Scripts/easy_install.exe %PYWIN_PATH%"
  - ps: (& "$env:PYTHON/python.exe" -m pip install --upgrade pip virtualenv)
  - ps: '& "$env:PYTHON/Scripts/pip.exe" install -r requirements-dev.txt'
  - ddev config set extras .
  # Remove the adodbapi module shipped with pywin32: it conflicts with the pip-installed adodbapi
  - ps: rm $env:PYTHON/lib/site-packages/$env:PYWIN32_INSTALL_DIR/adodbapi/__init__.py
  - ps: rm $env:PYTHON/lib/site-packages/$env:PYWIN32_INSTALL_DIR/adodbapi/__init__.pyc
build: off
test_script:
  - ddev -e test
