version: '{branch}.{build}'
image: Visual Studio 2017
clone_depth: 3
build: off
test: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'

skip_branch_with_pr: true
skip_tags: true
branches:
  only:
    - master

environment:
  PYTHON2: C:\Python27-x64
  PYTHON3: C:\Python37-x64

init:
  # Add Python 2 to PATH
  - set PATH=%PYTHON2%;%PYTHON2%\Scripts;%PATH%
  - python -c "import sys; print(sys.version)"

  # Add Python 3 to PATH before Python 2
  - set PATH=%PYTHON3%;%PYTHON3%\Scripts;%PATH%
  - python -c "import sys; print(sys.version)"

  # Test only what changed when it's a PR
  - if defined APPVEYOR_PULL_REQUEST_NUMBER ( set "CHANGED_ONLY_FLAG= --changed" ) else ( set "CHANGED_ONLY_FLAG= " )

  # Newer versions of Windows require this for full use of psutil
  - diskperf -y

install:
  - python -m pip install --upgrade --disable-pip-version-check pip virtualenv codecov
  - pip uninstall -y docker-py
  - pip install datadog_checks_dev[cli]
  - ddev config set extras .
  - ddev config set repo extras

test_script:
  - ddev validate manifest -i
  - ddev validate config
  - ddev validate service-checks
  - ddev validate metadata
  - ddev test%CHANGED_ONLY_FLAG% -c aqua eventstore sortdb
