trigger: none

pr:
  branches:
    include:
    - master

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip
  DDEV_COLOR: 1

resources:
  repositories:
    - repository: integrations-core
      type: github
      name: Datadog/integrations-core
      ref: florimondmanca/ci-cache-deps
      endpoint: DataDog

jobs:
- template: '.azure-pipelines/templates/test-single-linux.yml@integrations-core'
  parameters:
    job_name: Changed
    display: Linux
    validate: true
    repo: 'extras'
    pip_cache_config:
      key: 'pip | $(Agent.OS)'
      path: $(PIP_CACHE_DIR)

- template: '.azure-pipelines/templates/test-single-windows.yml@integrations-core'
  parameters:
    job_name: Changed
    check: '--changed none_yet'
    display: Windows
    repo: 'extras'
    pip_cache_config:
      key: 'pip | $(Agent.OS)'
      path: $(PIP_CACHE_DIR)
