name: Check markdown partials
# Checks for invalid markdown partials
on:
  pull_request:
    paths:
    - '**/*.md'

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      md: ${{ steps.changes.outputs.md }}
    steps:
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Output changed files
        id: changes
        run: |
          echo "::set-output name=md::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .md$ | xargs)"

  check_partials:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{needs.changed-files.outputs.md}}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Check for invalid partials
        run: |
          echo ${{needs.changed-files.outputs.md}}
          python .github/workflows/check_partials.py --files='${{ steps.changed_files.outputs.deleted_files }}'
